### ISSUE TITLE
How to setup a node to route all the network through another node?

### ISSUE THREAD

**Issue by gajus** [peervpn/peervpn#14]
I have two nodes that I have configured as:

Node A (the home computer):

```
psk test
enabletunneling yes
ifconfig4 10.8.0.1/24
```

Node B (my laptop):

```
psk test
initpeers ... 7000
enabletunneling yes
ifconfig4 10.8.0.2/24
```

How do I route all the laptop's (node B) network through the home computer (node A)?

**Comment by maxidor** [comment]
That configuration would be enough from a peervpn point of view.
The rest is up to the host configuration which is no different than having both computers directly wired to each other.
