### ISSUE TITLE
Raspberry Pi w/ Debian 9: long passkey not working

### ISSUE THREAD

**Issue by dadosch** [peervpn/peervpn#27]
I encountered the problem that with very long passkey peervpn is not connecting to other hosts, when run on Raspbian aka Debian Stretch. It just loops resolving and doesn't send a single network packet or error out.

It works fine with Ubuntu or Vanilla Debian 9 or Raspbian 8, but not with Raspbian 9.

I just wanted to let you know that.

**Comment by conrad784** [comment]
does [this](https://github.com/peervpn/peervpn/pull/20) pull request resolve your question?

**Comment by dadosch** [comment]
> does this pull request resolve your question?

yes, indeed it solved it. Thank you :+1: But why did it work fine with (vanilla) Debian 9, Ubuntu 16.04 and Raspbian 8? strange...
