### ISSUE TITLE
when running with dropped privileges name resolution will fail

### ISSUE THREAD

**Issue by fbartels** [peervpn/peervpn#5]
Hi Tobias,

when configuring peervpn to drop privileges after start, he complains about not beeing able to resolve the specified initpeers

The relevant section in my peervpn.conf looks like this:
```
enableprivdrop yes
user nobody
group nogroup
chroot /var/empty
```

And this is the error message:
```
PeerVPN v0.042
(c)2015 Tobias Volk <mail@tobiasvolk.de>


opening sockets...
   IPv4/UDP: ok.
   IPv6/UDP: failed.
opening TAP device...
   device "peervpn0": ok.
   done.
preparing P2P engine...
   done.

Client ID:  DBB6A94F8BE5019A94EC81BAB710F45762BA8A03BA4B70AA516A8493E7BD454B
Network ID: 8C4FD4F151BB4BDCD59912F8574EBB91239FDE1B6D642E179BA84EF1F21321C4

entering main loop...

[1] 0 peers connected.
[1] resolving example.net:7000...
             failed: name could not be resolved.
```

I was able to reproduce this on Ubuntu 14.04 (64bit) and Debian 7 (armv5tel) when calling peervpn with sudo.

Regards Felix

**Comment by tobiasvolk** [comment]
Hi,

this is a known issue. See the example peervpn.conf:

## Option:       chroot <directory>
## Description:  Specifies the directory that the PeerVPN process
##               will chroot to after initialization.
##               Note: Currently, DNS queries will not work anymore
##               if this option is enabled. The "initpeers" option
##               should only contain IP addresses in this case, not
##               domain names.
##               If unspecified, no chroot will be done.
## Example:      chroot /var/empty

The reason behind this is that PeerVPN relies on the libc for DNS resolving, which in turn needs access to files like /etc/resolv.conf etc. These files are obviously not accessible when chrooting into an empty directory.

If you need DNS resolving, you can either disable chrooting or copy over the required files into the chroot directory.
